name: 'Code Hobbit'
description: 'AI-powered CI integrator for your pull requests'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  processor:
    description: 'PR processor to use (dify, anthropic)'
    required: true
  include:
    description: 'Glob patterns for files to include'
    required: false
  exclude:
    description: 'Glob patterns for files to exclude'
    required: false
  max-changes:
    description: 'Maximum number of line changes to review per file'
    required: false
    default: '300'
runs:
  using: 'node20'
  main: 'dist/index.js'
