name: Test Action
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  process-acme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: |
          deno install

      - name: Build
        working-directory: packages/action
        run: deno task build

      - name: Run Acme processor
        uses: ./packages/action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          processor: 'acme'
          exclude: |
            ["**/dist/**", "deno.lock"]
          max-changes: "300"
