name: CI

on:
  # mainブランチへのpush時
  push:
    branches: [ main ]
  # プルリクエスト作成・更新時
  pull_request:

# ワークフローが必要とする権限
permissions:
  contents: read # actions/checkoutがリポジトリの内容を読み取るために必要

# ワークフローのジョブ定義
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 80 # カバレッジの閾値 (デフォルト80%)
    steps:
      # ステップ1: コードのチェックアウト (Composite Action を見つけるために必要)
      - name: Checkout code
        uses: actions/checkout@v4

      # ステップ2: Deno環境のセットアップ (Composite Actionを使用)
      - name: Setup Deno Environment
        uses: ./.github/actions/setup-deno # Use the composite action
        with:
          deno-version: 2.2.11

      # ステップ3: リンターの実行
      - name: Run Linter
        run: deno task lint

      # ステップ4: テストの実行とカバレッジデータの生成
      - name: Run Tests with Coverage
        run: deno task test:cov

      # ステップ5: カバレッジ閾値のチェック（VeryGoodOpenSourceのアクション使用）
      - name: Check Coverage Threshold
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ./cov/lcov.info
          min_coverage: ${{ env.COVERAGE_THRESHOLD }}

  build:
    runs-on: ubuntu-latest
    # 依存ジョブ (testジョブが成功した後に実行)
    needs: test
    steps:
      # ステップ1: コードのチェックアウト (Composite Action を見つけるために必要)
      - name: Checkout code
        uses: actions/checkout@v4

      # ステップ2: Deno環境のセットアップ (Composite Actionを使用)
      - name: Setup Deno Environment
        uses: ./.github/actions/setup-deno # Use the composite action
        with:
          deno-version: 2.2.11

      # ステップ3: GitHub Actionのビルド
      - name: Build GitHub Action
        run: deno task build:action